### ISSUE TITLE
NoSuchMethod & Abstract method crashes in dev

### ISSUE THREAD

**Issue by LemADEC** [TheCBProject/ForgeMultipart#50]
As of Forge 14.23.5.2796, mappings stable_39, CodeChickenLib-1.12.2-3.2.2.353-deobf, and ForgeMultipart-1.12.2-2.6.0.79-deobf, game will crash on launch due to invalid reference to abstract method setUnlocalizedName().

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Forge Microblocks (microblockcbe)
Caused by: java.lang.NoSuchMethodError: codechicken.microblock.ItemMicroPart.setUnlocalizedName(Ljava/lang/String;)Lnet/minecraft/item/Item;
	at codechicken.microblock.ItemMicroPart.<init>(ItemMicroPart.scala:29)
	at codechicken.microblock.handler.MicroblockProxy_serverImpl.preInit(proxies.scala:45)
	at codechicken.microblock.handler.MicroblockProxy_clientImpl.preInit(proxies.scala:103)
	at codechicken.microblock.handler.MicroblockMod$.preInit(MicroblockMod.scala:16)
	at codechicken.microblock.handler.MicroblockMod.preInit(MicroblockMod.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:626)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
https://gist.github.com/LemADEC/0de8fe5ab8e7d50ae056bfab30776843

Using the objuscated versions crash later on during block ticking (here with the translocator mod):
```
Description: Ticking block entity

java.lang.AbstractMethodError
	at net.minecraft.world.World.updateEntities(World.java:2019)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:643)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:842)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:2019)

-- Block entity being ticked --
Details:
	Name: ccmp:saved_multipart // TileMultipart_cmp$$0
	Block type: ID #253 (tile.null // codechicken.multipart.BlockMultipart // forgemultipartcbe:multipart_block)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-519,12,-773), Chunk: (at 9,0,11 in -33,-49; contains blocks -528,0,-784 to -513,255,-769), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Actual block type: ID #253 (tile.null // codechicken.multipart.BlockMultipart // forgemultipartcbe:multipart_block)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:2019)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:643)
```

**Comment by covers1624** [comment]
My `deobf` jars are produced with the mappings i build against, currently that is `snapshot_20171003`. I use a really old version for many reasons, mainly because my Workspace is setup for base editing, meaning i can edit all of forge and minecraft in dev. I would recommend using `deobfCompile` on the `universal` jars but i believe there are some obfuscation issues with FMP's mixin compiler, at the moment just use the same mappings as FMP and `deobf` jars.

**Comment by LemADEC** [comment]
My project was changed for those mappings around July 2018, while refreshing by gradle scripts.
Since then, other mods have been impacted by API changes in Forge, so rolling back my project mappings isn't no longer option.
