### ISSUE TITLE
Apparent issue between ChickenLib and Multipart CBE

### ISSUE THREAD

**Issue by UK-IN-US** [TheCBProject/ForgeMultipart#54]
I've had a variety of different crash reports, but I'll attach two examples here.  Basically, what it looks like is going on is that Multipart CBE is trying to call a method or class or _something_ from ChickenLib that's not defined.  I'm likely wrong though, my knowledge of Java is limited at best.  Any help in resolving this would be much appreciated.

[crash-2019-02-06_18.33.24-server.txt](https://github.com/TheCBProject/ForgeMultipart/files/2838865/crash-2019-02-06_18.33.24-server.txt)
[crash-2019-02-06_18.25.31-server.txt](https://github.com/TheCBProject/ForgeMultipart/files/2838866/crash-2019-02-06_18.25.31-server.txt)

Relevant section pulled out:
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Forge Multipart CBE (forgemultipartcbe)
Caused by: java.lang.NoClassDefFoundError: codechicken/asm/ASMHelper
	at codechicken.multipart.asm.ASMMixinCompiler$.classNode(ASMMixinCompiler.scala:117)
	at codechicken.multipart.asm.ASMMixinFactory.registerTrait(ASMMixinFactory.scala:58)
	at codechicken.multipart.asm.ASMMixinFactory.registerTrait(ASMMixinFactory.scala:55)
	at codechicken.multipart.MultipartGenerator$.<init>(MultipartGenerator.scala:32)
	at codechicken.multipart.MultipartGenerator$.<clinit>(MultipartGenerator.scala)
	at codechicken.multipart.handler.MultipartProxy_serverImpl.preInit(proxies.scala:37)
	at codechicken.multipart.handler.MultipartMod$.preInit(MultipartMod.scala:16)
	at codechicken.multipart.handler.MultipartMod.preInit(MultipartMod.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: codechicken.asm.ASMHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.NullPointerException

**Comment by covers1624** [comment]
Forge apparently isnt extracting ChickenASM from inside the FMP jar, Please attach your full debug launch log.

**Comment by UK-IN-US** [comment]
[debug-3.log.gz](https://github.com/TheCBProject/ForgeMultipart/files/2847852/debug-3.log.gz)

**Comment by covers1624** [comment]
The provided log doesnt show FMP being loaded at all. Likely a user error or corrupted jar file.
